spring:
  application:
    name: product-service
server:
  port: 10002
      
dubbo:
  registry:
    id: product-service
    address: zookeeper://127.0.0.1:2181
    group: local
  application:
    name: product-service
    id: product-service
    logger: slf4j
    qosEnable: true
    qosPort: 20002
    qosAcceptForeignIp: false
  protocol:
    # -1表示使用随机未被占用的端口
    port: -1
    name: dubbo
  scan:
    # dubbo 服务提供者实现类所在包
    base-packages: com.liyulin.dubbo.demo.product.service